# fly.toml app configuration file generated for momentum-api-stage on 2024-08-30T13:01:51-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'momentum-api-stage'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.stage'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
