name: Azure Development Deploy

on:
  push:
    branches:
      - main
    paths:
      - "ui/**"
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "ui/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run deploy:dev
        run: |
          npm run deploy:dev
        env:
          AZURE_ACCESS_TOKEN: ${{ secrets.AZURE_DEPLOYMENT_ACCESS_TOKEN }}
