name: Azure Static Web Apps CI/CD
# On push to "prod" branch or PR closed/merged, build and deploy to Azure Static Web App Production
# On push to "main" branch, build and deploy to Azure Static Web App Development

on:
  push:
    branches:
      - main
      - prod
    paths:
      - "ui/**"
  pull_request:
    types: [closed]
    branches:
      - prod

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_FLOWER_0BC214C0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./ui"
          app_build_command: "npm run build:prod"
          output_location: "dist/prod/browser"
          production_branch: "prod"
