name: Azure SWA Development Deployment

on:
  push:
    branches:
      - main
    paths:
      - "ui/**"
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "ui/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.X"

      # Install npm dependencies
      - name: Install dependencies
        run: |
          cd ui
          npm install
          npm install -g @azure/static-web-apps-cli

      # Build app
      - name: Build app
        run: |
          cd ui
          npm run build:dev
          ls -la dist/ui/browser

      # Deploy to Azure using SWA CLI
      - name: Deploy using SWA CLI
        run: |
          cd ui
          swa deploy dev --env dev --deployment-token ${{ secrets.AZURE_DEPLOYMENT_ACCESS_TOKEN }}
      # swa deploy `config name` --env `swa preview name`  --deployment-token `token`
