name: Fly.io Development Deployment
# On push to "main" branch, build and deploy to Fly.io Development

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: iad
  FLY_ORG: cheapgpt

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      # Only allow one deployment at a time on `main`.
      group: main-deployment

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Deploy DEV API to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          config: ./api/fly.dev.toml
